version: '3.9'
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - Heepoke
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo-api
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - Heepoke

networks:
  Heepoke:
    driver: bridge